### ISSUE TITLE
Avoid uninteresting/repeated responses

### ISSUE THREAD

**Issue by giorgiovilardo** [ivoputzer/slack.codin.gg#5]
In some cases bot produces uninteresting responses like repeating the same word over and over.

This is very detrimental to the chat flow, as it usually make the screen scroll.

A potential fix could be to make a `Set()` of the response splitted on spaces and `\n`s, and if the length of the set does not pass some minimum threshold quantity (1? 2?), log the message and output just a list of the set words in chat.

Todo: see if it's a costly operation in terms of time complexity, specially on big text chunks answers? Find another, better, implementation?

**Comment by giorgiovilardo** [comment]
maybe doable via conf:

![image](https://user-images.githubusercontent.com/56472600/151586272-b2de3d7c-fc95-4a60-9835-324f29cf5861.png)

https://beta.openai.com/docs/api-reference/completions/create#completions/create-presence_penalty

https://beta.openai.com/docs/api-reference/parameter-details

**Comment by ivoputzer** [comment]
Most of the time this happens when bot doesn't have enough context and user is writing a very short text to which davinci cannot accurately predict the best possibile outcome of the conversation. so he starts having a conversation with himself 🤣 or replying gibberish.

I was exploring the possibility to attach some more context to each incoming slack message along with a set a predefined variables such as a mood [slack slash command](https://api.slack.com/interactivity/slash-commands) `/mood` : `sarcastic`, `helpful`, `creative`, `clever`, `very friendly` to set the mood of the conversation.

```
{bot:name} is a chatbot that answers questions with {bot:mood} responses: 

{channel:previous:user}: {channel:previous:message}
{bot:name}: {bot:previous_response}
{channel:current:user}: {channel:current:message}
{bot:name}: 
```

issue here is identifying proper stops to make davinci behave as expected and extract only the relevant response part. another risk here is davinci will continue the conversation all by himself 😂 

---

FYI @giorgiovilardo i added a command line utility to the project so that experimenting with user inputs doesn't require the whole application to be deployed and used via slack directly. 

```
npm install; npm run prompt
```

only thing is to provide an openai secret via .npmrc or directly as an option to the command.

**Comment by ivoputzer** [comment]
conversation context has been added to #8. Let's see and verify if we can integrate this to the slackbot as well.

**Comment by giorgiovilardo** [comment]
I totally forgot about this

btw I don't have an openai secret, I'm a poor kid

**Comment by ivoputzer** [comment]
should be open to everyone now you just need an email and a phone number 😄

**Comment by ivoputzer** [comment]
i upgraded `gpt 3.5-turbo` yesterday, which is slightly less expensive; we should have gotten rid of context unaware responses by now. temporarily closing the issue
